version: '3'

services:
  cheestore:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cheestore
      - cheestore_static_volume:/cheestore/static
      - cheestore_files_volume:/cheestore/files
    restart: always
    ports:
      - "8000:8000"
    networks:
      - cheestore_network
      - nginx_network
    depends_on:
      - cheestore_postgresql
    # command: ["python","./manage.py", "runserver", "8000"]

  cheestore_postgresql:
    image: postgres:10
    container_name: cheestore_postgresql
    volumes:
      - cheestore_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - cheestore_network

volumes:
  cheestore_postgresql:
    external: true
  cheestore_static_volume:
    external: true
  cheestore_files_volume:
    external: true
networks:
  cheestore_network:
    external: true
  nginx_network:
    external: true


