# Generated by Django 3.2.5 on 2022-07-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'لیسانس'), ('Phd', 'دکترا'), ('Master', 'فوق لیسانس'), ('Undergraduate', 'زیر دیپلم')], max_length=15, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Partner', 'همسر'), ('Child', 'فرزند')], max_length=7),
        ),
    ]
