# Generated by Django 3.2.5 on 2022-07-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220718_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('Master', 'فوق لیسانس'), ('Bachelor', 'لیسانس'), ('Undergraduate', 'زیر دیپلم'), ('Phd', 'دکترا')], max_length=15, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Child', 'فرزند'), ('Partner', 'همسر')], max_length=7),
        ),
    ]
