# Generated by Django 3.2.5 on 2022-07-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220718_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'زیر دیپلم'), ('Master', 'فوق لیسانس'), ('Bachelor', 'لیسانس'), ('Phd', 'دکترا')], max_length=15, null=True, verbose_name='مدرک تحصیلی'),
        ),
    ]
