# Generated by Django 3.2.5 on 2022-07-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220718_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Child', 'فرزند'), ('Partner', 'همسر')], max_length=7),
        ),
    ]
