# Generated by Django 3.2.5 on 2022-07-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_familymember_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('Master', 'فوق لیسانس'), ('Undergraduate', 'زیر دیپلم'), ('Phd', 'دکترا'), ('Bachelor', 'لیسانس')], max_length=15, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Partner', 'همسر'), ('Child', 'فرزند')], max_length=7),
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='occasion',
            field=models.CharField(choices=[('birthday', 'birthday'), ('anniversary', 'anniversary')], max_length=11),
        ),
    ]
