# Generated by Django 3.2.5 on 2022-07-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220718_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('Phd', 'دکترا'), ('Master', 'فوق لیسانس'), ('Undergraduate', 'زیر دیپلم'), ('Bachelor', 'لیسانس')], max_length=15, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='occasion',
            field=models.CharField(choices=[('anniversary', 'anniversary'), ('birthday', 'birthday')], max_length=11),
        ),
    ]
