# Generated by Django 3.2.5 on 2022-07-17 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام جایزه')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('allowed_to_used', models.PositiveSmallIntegerField(verbose_name='تعداد دسترسی به جوایز')),
                ('allowed_to_used_duration', models.IntegerField(choices=[(1, 'day'), (30, 'month'), (365, 'year'), (7, 'week')], verbose_name='مدت اعتبار')),
                ('detail', models.CharField(max_length=2000, verbose_name='جزئیات ')),
                ('image', models.ImageField(upload_to='project/static', verbose_name='عکس جایزه')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت جایزه')),
                ('worth', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='ارزش')),
            ],
            options={
                'verbose_name': 'جوایز',
                'verbose_name_plural': 'جوایز ها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, default='profile', max_length=100, null=True)),
                ('is_gold', models.BooleanField(default=False)),
                ('score_user', models.IntegerField(default=0, verbose_name='تعداد امتیاز')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها ',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن ')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='CustomerClub.gift', verbose_name='نام جایزه انتخاب شده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to=settings.AUTH_USER_MODEL, verbose_name='ت')),
            ],
        ),
    ]
