# Generated by Django 3.2.5 on 2022-07-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerClub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='allowed_to_used_duration',
            field=models.IntegerField(choices=[(365, 'year'), (1, 'day'), (30, 'month'), (7, 'week')], verbose_name='مدت اعتبار'),
        ),
    ]
