# Generated by Django 3.2.5 on 2022-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerClub', '0003_alter_gift_allowed_to_used_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='logs',
            field=models.CharField(blank=True, default='history', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='allowed_to_used_duration',
            field=models.IntegerField(choices=[(365, 'year'), (1, 'day'), (7, 'week'), (30, 'month')], verbose_name='مدت اعتبار'),
        ),
    ]
