# Generated by Django 3.2.5 on 2022-07-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerClub', '0004_auto_20220717_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='score_log',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='allowed_to_used_duration',
            field=models.IntegerField(choices=[(1, 'day'), (7, 'week'), (365, 'year'), (30, 'month')], verbose_name='مدت اعتبار'),
        ),
    ]
