# Generated by Django 3.2.5 on 2022-07-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerClub', '0005_auto_20220717_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='allowed_to_used_duration',
            field=models.IntegerField(choices=[(365, 'year'), (30, 'month'), (7, 'week'), (1, 'day')], verbose_name='مدت اعتبار'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
