# Generated by Django 3.2.5 on 2022-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerClub', '0006_auto_20220717_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='activities',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='allowed_to_used_duration',
            field=models.IntegerField(choices=[(30, 'month'), (1, 'day'), (365, 'year'), (7, 'week')], verbose_name='مدت اعتبار'),
        ),
    ]
