# Generated by Django 3.2.5 on 2022-07-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerClub', '0007_auto_20220718_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='allowed_to_used_duration',
            field=models.IntegerField(choices=[(365, 'year'), (30, 'month'), (1, 'day'), (7, 'week')], verbose_name='مدت اعتبار'),
        ),
    ]
