# Generated by Django 3.2.5 on 2022-07-18 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CustomerClub', '0013_alter_gift_allowed_to_used_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='activities',
        ),
        migrations.AlterField(
            model_name='gift',
            name='allowed_to_used_duration',
            field=models.IntegerField(choices=[(365, 'year'), (7, 'week'), (1, 'day'), (30, 'month')], verbose_name='مدت اعتبار'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
